### ISSUE TITLE
Create instance of IUowProvider in Singleton class

### ISSUE THREAD

**Issue by anhlee24** [digipolisantwerp/dataaccess_aspnetcore#18]
How can i create an instance of IUowProvider?

I have a singleton class like this and need to create instance:

` 
public class SystemConfig : ISystemConfig

      {
        private static SystemConfig SystemConfigInstance = new SystemConfig(default(UowProvider));// problem here

       public SystemConfig(IUowProvider uowProvider)
        {
            _uowProvider = uowProvider;
       `}

        public static SystemConfig GetInstace()
        {
            if (SystemConfigInstance == null)
            {
                lock (typeof(SystemConfig))
                {
                    if (SystemConfigInstance == null)
                    {
                        SystemConfigInstance = new SystemConfig(default(UowProvider));
                    }
                    
                }
            }
            return SystemConfigInstance;
        }
     }

**Comment by StevenVandenBroeck** [comment]
A better way to make singletons is to use the dependency injection framework. Just make a normal class and register it as a singleton during Startup : 

`services.AddSingleton<MyInterface, MyClass>();`

In this class you inject the IUowProvider via the constructor and the dependency injection framework will instantiate it, since it is also registered (as a singleton actually) : 

https://github.com/digipolisantwerp/dataaccess_aspnetcore/blob/development/src/Digipolis.DataAccess/Startup/ServiceCollectionExtensions.cs

You can find more on the dependency injection framework in .NET Core [docs](https://docs.asp.net/en/latest/fundamentals/dependency-injection.html). Look for the lifetime [section](https://docs.asp.net/en/latest/fundamentals/dependency-injection.html#service-lifetimes-and-registration-options)

**Comment by anhlee24** [comment]
Thank you! My problem resovled!
